In [127]:
import os
import string
from collections import defaultdict
import re
import numpy as np
import pandas as pd

np.random.seed(42)

In [128]:
def load_data(path: str):
    df = pd.read_csv(path)
    df = df[df["species"] != 'Virginica']
    return df.to_numpy()

In [129]:
data = load_data("./dataset/iris.csv")
data

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [5.0, 3.0, 1.6, 0.

In [130]:
def train_test_split(data, train_split_ratio):
    np.random.shuffle(data)
    train_count = int(data.shape[0] * train_split_ratio)
    train = data[:train_count]
    test = data[train_count:]
    X_train = train[:, :4].astype(float)
    y_train = train[:, 4]
    X_test = test[:, :4].astype(float)
    y_test = test[:, 4]
    return X_train, y_train, X_test, y_test

In [131]:
def encode_labels(labels):
    return np.where(labels=="setosa", 1, -1)

In [132]:
def binary_cross_entropy(y_true, y_pred):
    m = y_true.shape[0]
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    # Calculating loss
    loss = -1/m * (np.dot(y_true.T, np.log(y_pred)) + np.dot((1 - y_true).T, np.log(1 - y_pred)))

    return loss

# def binary_cross_entropy(y_true, y_pred):
#     return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [133]:
X_train, y_train, X_test, y_test = train_test_split(data, train_split_ratio=0.9)
X_train, y_train, X_test, y_test

(array([[6. , 2.7, 5.1, 1.6],
        [5.5, 2.3, 4. , 1.3],
        [5.9, 3.2, 4.8, 1.8],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.9, 0.4],
        [5.1, 3.4, 1.5, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [5.5, 2.4, 3.8, 1.1],
        [5.4, 3.7, 1.5, 0.2],
        [5.1, 3.5, 1.4, 0.2],
        [5.7, 3.8, 1.7, 0.3],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.8, 4.7, 1.2],
        [5.5, 4.2, 1.4, 0.2],
        [5.5, 2.6, 4.4, 1.2],
        [5. , 3.6, 1.4, 0.2],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [4.8, 3. , 1.4, 0.1],
        [5.4, 3.4, 1.5, 0.4],
        [5.7, 2.8, 4.5, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5. , 3.4, 1.6, 0.4],
        [4.4, 3.2, 1.3, 0.2],
        [5.6, 2.5, 3.9, 1.1],
        [5.7, 4.4, 1.5, 0.4],
        [5. , 3.5, 1.3, 0.3],
        [5.7, 2.9, 4.2, 1.3],
        [4.9, 3.1, 1.5, 0.1],
        [6.3, 2.5, 4.9, 1.5],
        [4.8, 3.4, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [6. , 3.4, 4.5, 1.6],
        [5

In [134]:
def train(data, labels, epochs, learning_rate):
    num_features = len(data[0])
    weights = np.random.uniform(-0.5, 0.5, num_features)
    bias = np.random.uniform(-0.5, 0.5)

    def activation(x):
        return 1 if x >= 0 else -1

    for epoch in range(epochs):
        ok = 0
        y_pred = []
        for x, y in zip(data, labels):
            output = np.sum(weights * x) + bias
            prediction = activation(output)

            y_pred.append(prediction)
            if prediction != y:
                weights += x * y + learning_rate
                bias += learning_rate * y
            else:
                ok += 1
        # print(labels + 1, np.array(y_pred) + 1)
        loss = binary_cross_entropy(labels + 1, np.array(y_pred) + 1)
        print(f"Epoch {epoch+1}/{epochs} accuracy: {ok/len(data)} loss: {loss}")
    
    return weights, bias

In [135]:
weights, bias = train(X_train, encode_labels(y_train), epochs=15, learning_rate=0.1)
weights, bias

Epoch 1/15 accuracy: 0.9888888888888889 loss: 0.17909005057205682
Epoch 2/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 3/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 4/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 5/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 6/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 7/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 8/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 9/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 10/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 11/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 12/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 13/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 14/15 accuracy: 1.0 loss: 1.0000000494736468e-07
Epoch 15/15 accuracy: 1.0 loss: 1.0000000494736468e-07


(array([-6.2011576 , -2.38865805, -4.70982446, -1.39404003]),
 np.float64(0.326300878513349))

In [136]:
def test(data, labels, weights, bias):
    def activation(x):
        return 1 if x >= 0 else -1
    
    ok = 0
    for x, y in zip(data, labels):
        output = np.sum(weights * x) + bias
        prediction = activation(output)
        if prediction == y:
            ok += 1

    print(f"Accuracy test: {ok/len(data)}")

In [137]:
data, labels = load_data("./dataset/test")
data

PermissionError: [Errno 13] Permission denied: './dataset/test'

In [ ]:
labels = encode_labels(labels)
test(data, labels, weights, bias)

Accuracy test: 0.75


In [ ]:
# def test(weights, bias, text):
#     def activation(x):
#         return 1 if x >= 0 else -1

#     data = letter_freq(text)
#     output = np.sum(weights * data) + bias
#     prediction = activation(output)
#     return "en" if prediction == 1 else "it"

In [ ]:
# text = "SMS Friedrich Carl was an armored cruiser of the Imperial German Navy. A member of the Prinz Adalbert class, the ship was intended to act as a scout for the fleet's battleships and to patrol the German colonial empire. The Prinz Adalbert class was based on the earlier armored cruiser Prinz Heinrich, but with improved armament and armor. Built in the early 1900s, Friedrich Carl served in the German fleet from 1904 to 1909, which included a period as flagship of the reconnaissance squadron and a cruise to the Mediterranean Sea."
# test(weights, bias, text)

In [ ]:
# text = "that Samuel Lander founded the Williamston Female College in an abandoned hotel?"
# test(weights, bias, text)

In [ ]:
# text = "Operazione Quercia (in tedesco Unternehmen Eiche) fu il nome in codice dato all'operazione militare condotta il 12 settembre 1943 dai paracadutisti tedeschi della 2. Fallschirmjäger-Division che portò alla liberazione di Benito Mussolini dalla prigionia a Campo Imperatore, sul Gran Sasso. Dopo essere stato arrestato il 25 luglio 1943, Mussolini venne condotto in varie località e alla fine trasferito a Campo Imperatore a fine estate del 1943, una zona isolata e raggiungibile solo tramite funivia, dove era guardato a vista. Per non rischiare di farlo cadere in mano agli Alleati, Adolf Hitler ordinò al generale dei paracadutisti Kurt Student di organizzare una missione per la liberazione del Duce servendosi dei suoi Fallschirmjäger, a cui vennero aggregati, per ragioni politiche, sedici uomini del Servizio di sicurezza (Sicherheitsdienst - SD) delle SS agli ordini del capitano Otto Skorzeny."
# test(weights, bias, text)

In [ ]:
# text = "Il 12 settembre, pochi giorni dopo il Proclama Badoglio che annunciava la resa incondizionata delle forze italiane agli Alleati, i paracadutisti tedeschi lanciarono un audace assalto per liberare Mussolini, che si risolse con successo e senza perdite per gli assalitori. Grazie ai suoi contatti diretti con Ernst Kaltenbrunner e Heinrich Himmler, fin da subito Skorzeny riuscì a imporre la propria versione distorta e autocelebrativa dei fatti avvenuti sul Gran Sasso"
# test(weights, bias, text)

In [ ]:
for lr in [1, 0.1, 0.01, 0.001, 0.0001]:
    print(lr, 30 * "*")
    data, labels = load_data("./dataset/train")
    encoded_labels = encode_labels(labels)

    weights, bias = train(data, encoded_labels, epochs=15, learning_rate=lr)
    data, labels = load_data("./dataset/test")
    labels = encode_labels(labels)
    test(data, labels, weights, bias)

1 ******************************
Epoch 1/15 accuracy: 0.5
Epoch 2/15 accuracy: 0.6666666666666666
Epoch 3/15 accuracy: 1.0
Epoch 4/15 accuracy: 1.0
Epoch 5/15 accuracy: 1.0
Epoch 6/15 accuracy: 1.0
Epoch 7/15 accuracy: 1.0
Epoch 8/15 accuracy: 1.0
Epoch 9/15 accuracy: 1.0
Epoch 10/15 accuracy: 1.0
Epoch 11/15 accuracy: 1.0
Epoch 12/15 accuracy: 1.0
Epoch 13/15 accuracy: 1.0
Epoch 14/15 accuracy: 1.0
Epoch 15/15 accuracy: 1.0
Accuracy test: 0.7
0.1 ******************************
Epoch 1/15 accuracy: 0.16666666666666666
Epoch 2/15 accuracy: 0.16666666666666666
Epoch 3/15 accuracy: 0.0
Epoch 4/15 accuracy: 0.16666666666666666
Epoch 5/15 accuracy: 0.0
Epoch 6/15 accuracy: 0.16666666666666666
Epoch 7/15 accuracy: 0.0
Epoch 8/15 accuracy: 0.3333333333333333
Epoch 9/15 accuracy: 0.16666666666666666
Epoch 10/15 accuracy: 0.3333333333333333
Epoch 11/15 accuracy: 1.0
Epoch 12/15 accuracy: 1.0
Epoch 13/15 accuracy: 1.0
Epoch 14/15 accuracy: 1.0
Epoch 15/15 accuracy: 1.0
Accuracy test: 0.7
0.01 **